Fix launch files and scripts, add for drive

diff --git a/arm-upload b/arm-upload
--- a/arm-upload
+++ b/arm-upload
@@ -1,7 +1,7 @@
 #!/usr/bin/zsh
 
-if [[ -f /home/robotics/rover/Arduino/CMakeLists.txt ]]; then
-    (cd /home/robotics/rover/Arduino && rm -rf build && mkdir build && cd build && cmake .. && make arm-upload ) || (echo "Failed to upload code" && exit 1)
+if [[ -f ~/rover/Arduino/CMakeLists.txt ]]; then
+    (cd ~/rover/Arduino && rm -rf build && mkdir build && cd build && cmake .. && make arm-upload ) || (echo "Failed to upload code" && exit 1)
 else
     echo "Could not find the arduino folder"
     exit 1
